services:
  backend:
    build:
      context: ./backend
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: backend
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    image: node:20.15.0
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  sqlite_data:
